#!/usr/bin/env bash
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
cd "$REPO_ROOT"

export TRASHFORMER_AUTOSTART_RUNTIME="${TRASHFORMER_AUTOSTART_RUNTIME:-1}"
export TRASHFORMER_RUNTIME_DRIVE_OUTPUTS="${TRASHFORMER_RUNTIME_DRIVE_OUTPUTS:-1}"
export TRASHFORMER_RUNTIME_STABLE_HOLD_SECONDS="${TRASHFORMER_RUNTIME_STABLE_HOLD_SECONDS:-2.0}"
export TRASHFORMER_RUNTIME_MIN_CONFIDENCE="${TRASHFORMER_RUNTIME_MIN_CONFIDENCE:-0.60}"
export TRASHFORMER_RUNTIME_BUZZER_MODE="${TRASHFORMER_RUNTIME_BUZZER_MODE:-passive}"
export TRASHFORMER_RUNTIME_STANDBY_REMINDER_SECONDS="${TRASHFORMER_RUNTIME_STANDBY_REMINDER_SECONDS:-20}"
export TRASHFORMER_RUNTIME_CATEGORY_HOLD_SECONDS="${TRASHFORMER_RUNTIME_CATEGORY_HOLD_SECONDS:-2.0}"
export TRASHFORMER_RUNTIME_CAMERA_WIDTH="${TRASHFORMER_RUNTIME_CAMERA_WIDTH:-1280}"
export TRASHFORMER_RUNTIME_CAMERA_HEIGHT="${TRASHFORMER_RUNTIME_CAMERA_HEIGHT:-720}"
export TRASHFORMER_RUNTIME_CAMERA_TIMEOUT_MS="${TRASHFORMER_RUNTIME_CAMERA_TIMEOUT_MS:-1000}"
export TRASHFORMER_CAPTURE_EMPTY_ON_START="${TRASHFORMER_CAPTURE_EMPTY_ON_START:-1}"

if [[ "${TRASHFORMER_CAPTURE_EMPTY_ON_START}" =~ ^(1|true|yes|on)$ ]]; then
  /usr/bin/python3 scripts/pi/capture_empty_reference.py \
    --camera-arg=--width \
    --camera-arg="${TRASHFORMER_RUNTIME_CAMERA_WIDTH}" \
    --camera-arg=--height \
    --camera-arg="${TRASHFORMER_RUNTIME_CAMERA_HEIGHT}" \
    --camera-arg=--timeout \
    --camera-arg="${TRASHFORMER_RUNTIME_CAMERA_TIMEOUT_MS}"
fi

exec .venv/bin/python apps/trashformer_app/backend/server.py
